# Site settings
author: David Munro
title: Munro Musings
header-img: img/home-bg.png
email: dbhmunro@gmail.com
copyright_name: David Munro
description: > # this means to ignore newlines until "baseurl:"
  Perspectives from a Software Engineer Student
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Dbhmunro

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
